//! V1 Pipeline
pub(crate) mod cli;
pub(crate) mod hir;
pub(crate) mod interpret;
pub(crate) mod lir;
pub(crate) mod llvm_codegen;
pub(crate) mod lower;
pub(crate) mod mir;
pub(crate) mod nir;
pub(crate) mod sir;
